name: window_self_host

on:
  workflow_dispatch: 
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'

jobs:
  ant_build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Build with Ant
        run: |          
          ls
          cd C:\Users\sykwon\Downloads\apache-ant-1.10.13\bin\
          .\ant -noinput -buildfile C:\Users\sykwon\Documents\actions-runner\_work\self-host_window\self-host_window\build/build.xml       
      - uses: actions/upload-artifact@v3
        with:
          name: testwar
          path: build/build/helloworld-0.1-dev.war  

  move:
    name: move
    runs-on: self-hosted
    needs: ant_build
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: testwar
      - name: test
        run: |
          ls
          scp helloworld-0.1-dev.war kwon@192.168.8.204:\users\kwon\
          ssh kwon@192.168.8.204 cp C:\Users\kwon\helloworld-0.1-dev.war '\Program Files\apache-tomcat\webapps'

