name: window_self_host

on:
  workflow_dispatch: 
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'

jobs:
  ant_build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Build with Ant
        run: |          
          dir
          C:\Users\sykwon\Downloads\apache-ant-1.10.12\bin\ant -noinput -buildfile build/build.xml
        shell: cmd
      - uses: actions/upload-artifact@v3
        with:
          name: testwar
          path: build/build/helloworld-0.1-dev.war  
